trigger:
  branches:
      include:
        - development
        - master

variables:

  # Solution Variables
  buildPlatform: 'x64'
  buildProjects: '**/Fix.Management*.csproj'
  publishFixManagementServerlessApi: '**/Fix.Management.ServerlessApi.csproj'
  publishFixManagementTriggers: '**/Fix.Management.Triggers.csproj'
  buildConfiguration: 'Release'

  # Version Handling Variables
  majorProductVersion: 1   
  minorProductVersion: 0
  
  # Artifact Drop Folder
  artifactName: 'drop'

- job: Build_Fix_Management_Projects
  pool:
    vmImage: 'windows-2019'
    displayName: 'Run Main Build'

  steps:
  # Installer
  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 4.4.1'
    inputs:
      versionSpec: '4.4.1'
  
  # Specify sdk Version
  - task: UseDotNet@2
    displayName: 'Use sdk 3.1.102'
    inputs:
      packageType: 'sdk'
      version: '3.1.102'
  
  # Restore
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(buildProjects)'
      includeNuGetOrg: true
      nobuild: true
  
  # Build
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '$(buildProjects)'
      arguments: '--configuration $(buildConfiguration) --no-restore'
  
  # Publish Fix Management Serverless API
  - task: DotNetCoreCLI@2
    displayName:  Publish Fix Management Serverless API
    inputs:
      command: publish
      publishWebProjects: false
      projects: '$(publishFixManagementServerlessApi)'
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory) --no-restore'
      zipAfterPublish: true

  # Publish Fix Management Triggers
  - task: DotNetCoreCLI@2
    displayName: Publish Fix Management Triggers
    inputs:
      command: publish
      publishWebProjects: false
      projects: '$(publishFixManagementTriggers)'
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory) --no-restore'
      zipAfterPublish: true

  # Publish PDBs
  - task: PublishSymbols@2
    displayName: 'Publish symbols path'
    inputs:
      SearchPattern: '*\bin**.pdb'
      PublishSymbols: false
    continueOnError: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: 'drop'