subscription_name = "FIXIT DEVELOPMENT"
subscription_id = "3584d483-cb9d-4104-a44f-bdbf013ba934"
environment_name = "dev"
location_name = "canadacentral"
location_name_linux = "eastus"
cms_connection_string = "DefaultEndpointsProtocol=https;AccountName=fixitdevchms;AccountKey=1irp3z2m2uMXmvVqIp5mmgFIsChweA3m3uQhXFhwadTKkbpZIC6W2YMVmwVxFZCTECD9OXklp+6UjfEaRYWGkg==;EndpointSuffix=core.windows.net"