subscription_name = "FIXIT DEVELOPMENT"
subscription_id = "3584d483-cb9d-4104-a44f-bdbf013ba934"
environment_name = "dev"
location_name = "canadacentral"
location_name_linux = "eastus"
cms_connection_string = "DefaultEndpointsProtocol=https;AccountName=fixitdevcms;AccountKey=ERximDmMBUzWLN2UVUotMj1ZbZvylVPybyYjgnnip5mg+bCj686hugVlAAg1d+xDtrPRagMNKS2O9pphVpR2/g==;EndpointSuffix=core.windows.net"